### ISSUE TITLE
make a Scope here?

### ISSUE THREAD

**Issue by shashi** [piever/KaTeX.jl#2]
Is there a reason this package does not provide a widget to show and update a LaTeX string?

I'd love to use it for markdown in CSSUtil.

**Comment by piever** [comment]
I originally planned this just as a way to unify the download of KaTeX javascript, css, fonts and autorender extension (needed both for InteractBase and for Remark), but I agree it would make sense to move the LaTeX widgets here. I've opened the PR to "revamp" the LaTeX widgets at InteractBase https://github.com/piever/InteractBase.jl/pull/132 but I'm a bit stuck on asset loading issues. Happy to move those function here as soon as I understand how to load fonts and the autorender extension with AssetLoader (I may need some help there!).

**Comment by shashi** [comment]
Have a look at https://github.com/JuliaGizmos/CSSUtil.jl/blob/master/src/markdown.jl#L39 and see if it helps!

**Comment by piever** [comment]
The issue is that the CSSUtil code uses the online version of KaTeX whereas I would like to use a local copy. In the online version, it can find the font files easily are they are hosted in the same place as the katex.js file. However, with local files AssetServer "screws things up" by adding its prefixes and I get:

```
:8736/assetserver/fonts/KaTeX_Main-Regular.woff2:1 GET http://127.0.0.1:8736/assetserver/fonts/KaTeX_Main-Regular.woff2 net::ERR_ABORTED 500 (Internal Server Error)
```

**Comment by shashi** [comment]
Well you can register a directory with assetserver, it'll give you a url where all files in that directory will be served. KaTeX will load fonts from the same directory.

**Comment by shashi** [comment]
The error message makes this clear -- the katex.js is served under `assetserver/` directory which is why it looks for `assetserver/fonts/...`.

**Comment by piever** [comment]
Ah! I didn't know you could register a directory! I tried registering the fonts individually but it complained that the `.ttf` asset format was not supported....

**Comment by piever** [comment]
Opened #3, I called the function `latex` (not sure about the name) and it returns a scope: fonts should be loaded correctly, let me know if you have feedback before I merge.

**Comment by piever** [comment]
I was thinking, InteractBase `latex` could simply call this one (I like the idea that people just do `using Interact` and get all the functionality).
